### ISSUE TITLE
Is a JavaScript runtime a requirement in 3.x?

### ISSUE THREAD

**Issue by joostdecock** [envygeeks/jekyll-assets#495] opened 2018-02-02 15:39 UTC
- [X] I tried updating to the latest version.
  - [ ] I can't, there is an issue.
- [ ] I Am on Windows
- [ ] I Am on Bash on Windows
- [X] I Am on Linux
- [ ] I Am on OS X

## Description

I've been using jekyll-assets for a while now, mostly for compiling SCSS and bundling JS. Really basic stuff.

I've upgraded to 3.x, and I now get:

```
Assets:  Could not find a JavaScript runtime. See https://github.com/rails/execjs for a list of available runtimes.
```

## Steps

- Upgrade to assets 3
- `bundle exec jekyll build`

## Output

```sh
joost@mei:~/git/site$ bundle exec jekyll build -c _config/joost.yml
Configuration file: _config/joost.yml
            Source: /home/joost/git/site
       Destination: /home/joost/git/site/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
           Assets:  Compression is ignored w/ SourceMaps
           Assets:  Could not find a JavaScript runtime. See https://github.com/rails/execjs for a list of available runtimes.
  Liquid Exception: undefined method `[]' for nil:NilClass in /_layouts/notoc.html
jekyll 3.7.2 | Error:  undefined method `[]' for nil:NilClass

```

## Expected
The error is self-explanatory. My question is whether a JavaScript runtime is required, or can I work around it given that --- for my usecase --- there seems to be no need to execute any JS.

**Comment by envygeeks** [comment] 2018-02-09 12:29
Sorry for missing this issue.  Yes, we do require a JavaScript runtime environment by default, and I do not know if we can narrow it down to no requirement (read: bundling JavaScript with `//= require`.  We shouldn't be forcing it upon you though, can you rerun your site build with `--trace` so we can see where it's popping up at? There are some pieces where we should be detecting it and disabling it, and we might have a bad detector, or might be missing one (right now I'm going to assume in our compression.)

**Comment by envygeeks** [comment] 2018-02-09 12:30
I guess what I am saying is, I think it should be an optional requirement, but I don't know if it's possible anymore depending on which version of sprockets you're on.  But a trace would help me figure out if it's my fault and thus should fix that requirement as I don't necessarily want to force it on you, or if upstream has changed and I'll go with the flow.

**Comment by joostdecock** [comment] 2018-02-09 15:46
No apologies needed, we all have a ton of stuff to do. 

I have since installed the dependency, and moved on.  
If it is important to you to get to the bottom of this, I can setup a new environment, reproduce the issue, and run the trace.

But if you're like *nah* I'm happy to move on and consider this a non-issue.

Thank you for your great work. Much appreciated ❤️

**Comment by envygeeks** [comment] 2018-02-09 16:44
It would be nice to know, but it's not necessarily a big deal tbqf, I can let it go.  As I normally assume people will have JavaScript anyways because Jekyll kind of requires it, but kind of doesn't.  Thanks for the update!  I'll close this for now but if you ever remember and wanna update, I'll happily look into it.

**Comment by envygeeks** [comment] 2018-02-11 16:31
While I was in the source working on something else for a client I noticed that we indiscriminately enable compression for JavaScript regardless of situation.  So I've decided to fix this issue hoping that's the root cause.

**Closed** 2018-02-12 11:20 UTC
Labels: bug

**Comment by joostdecock** [comment] 2018-02-13 07:34
Thanks for this @envygeeks :+1:
