### ISSUE TITLE
Assets being proxied only one time

### ISSUE THREAD

**Issue by bronislav** [envygeeks/jekyll-assets#459] opened 2017-11-29 09:03 UTC
- [x] I tried updating to the latest version.
  - [x] I can't, there is an issue.
- [ ] I Am on Windows
- [ ] I Am on Bash on Windows
- [ ] I Am on Linux
- [x] I Am on OS X

## Description

When I use same asset (I'm my case image) with the same proxy options on the multiple pages, only last generated version being kept. In other words, I use image on three pages with same proxy settings, I see in logs that all three assets bairn written, but in the end only last one is beign kept.

## Steps

- Use asset with same settings on the several pages
- Check generated assets

## Expected

I've expect that all generated assets being kept and are accessible, but they are not.

**Comment by envygeeks** [comment] 2017-11-29 09:05
Please provide an example repository that replicates the issue.

**Comment by envygeeks** [comment] 2017-11-29 09:07
Also, if what you mean is that we only write a single asset, that is expected behavior, if you use the same source, with the same proxy settings, we do not run the proxy multiple times, we deliberately cache the asset, and you should get back the same digest, with the same url, every single time, regardless of where it is used, that is by design.

**Comment by bronislav** [comment] 2017-11-29 09:08
Yes, you are right. But it gets different digest every time I use it.

**Comment by envygeeks** [comment] 2017-11-29 09:11
That's because of #451.  Which is referencing this issue, and part of a larger problem with the way we handle pre-proxy setup, caching.  So I'm going to close this in favor of a single issue with multiple references.

**Closed by envygeeks** 2017-11-29 09:11 UTC
Labels: bug, pending-feedback
