### ISSUE TITLE
htaccess being wrongly parsed

### ISSUE THREAD

**Issue by gasparesganga** [envygeeks/jekyll-assets#461] opened 2017-11-29 11:30 UTC
- [x] I tried updating to the latest version.
  - [x] I can't, there is an issue.
- [ ] I Am on Windows
- [ ] I Am on Bash on Windows
- [x] I Am on Linux
- [ ] I Am on OS X

## Description
It seems that if you run an htaccess file through the parser some contents get deleted. As always, just to give more details, I'll add that this wasn't happening with v2.

### .htaccess_static *(without front matter)*
```
<FilesMatch ".(html|htm)$">
    ### Something here, it doesn't matter now
</FilesMatch>
```

### .htaccess *(with front matter)*
```
---
---
<FilesMatch ".(html|htm)$">
    ### Something here, it doesn't matter now
</FilesMatch>
```

### .htaccess_static *(without front matter)*
No front matter here, the FilesMatch filter is left untouched:
```
<FilesMatch ".(html|htm)$">
    ### Something here, it doesn't matter now
</FilesMatch>
```

### .htaccess *(with front matter)*
The FilesMatch filter is being altered (regex disappeared and lowercase tag):
```
<filesmatch>
    ### Something here, it doesn't matter now
</filesmatch>
```
Note how also the `<filesmatch>` tag is being lowercased in the parsed version.

**Comment by envygeeks** [comment] 2017-11-29 11:31
This is already fixed on head.

**Comment by envygeeks** [comment] 2017-11-29 11:31
Duplicate of #457

**Comment by gasparesganga** [comment] 2017-11-29 11:31
Great!

**Closed by envygeeks** 2017-11-29 11:31 UTC

**Comment by gasparesganga** [comment] 2017-11-29 11:36
Does the fix also include the decoding of **all** html entities used in templates? I was about to open another ticket, but it's most likely already fixed.
Example:
`&#110;&#111;&#115;&#112;&#097;&#109;&#104;&#101;&#114;&#101;&#064;&#101;&#120;&#097;&#109;&#112;&#108;&#101;&#046;&#099;&#111;&#109;`
get output as:
`nospamhere@example.com`

PS: I know that simple html entity encoding is doing nothing, that's just an example, not production use.

**Comment by envygeeks** [comment] 2017-11-29 11:38
You'll need to take that bug up with Nokogiri or accept it, if it's an HTML file.  There are no plans to prevent entity decoding as it's required unless it's within `<code>` or `<pre>`.  We use Nokogiri to enable enhanced features, and it's the one doing the converting.

**Comment by gasparesganga** [comment] 2017-11-29 11:42
Alright, no problem at all. That's definitely something I can live with.

**Comment by envygeeks** [comment] 2017-11-29 12:00
Yeah, I've double checked and there is no way for me to control whether or not it outputs entities.

**Comment by gasparesganga** [comment] 2017-11-29 12:10
This means you are going to prevent the decoding?
IMHO it's better to defer that to the user's browser, so disabling it would be the best choice for me. If somebody decided to use an entity instead of plain utf8 in his template, it should be left like that (just my opinion).

**Comment by envygeeks** [comment] 2017-11-29 12:13
Since we only support UTF-8 it will convert to UTF-8 if it can.  Which is the valid way to handle the modern web, which is encoding sensitive, so much so you now have to even set your encoding on the webpage, or it kicks up quirks mode, or fails validation.  Well it's been like that since i was a kid, but just recently turned to an error AFAIW.  That said, libxml2 is a pretty widely used library, I don't assume it doesn't know what it's doing.

**Comment by gasparesganga** [comment] 2017-11-29 12:19
You're right, there's actually no use for html entities in modern web, it makes sense 100%!

Time to move on :)  (I am a 1999 nostalgic...)
